export const URL = {
    BASE_URL: 'http://0.0.0.0:5000',
    LOGIN: "/user/login",
    REGISTER: "/user/register",
    VERIFY: "/user/verify",
    USER_PROFILE: "/user/profile",
    UPDATE_USER: "/user",
    WISHLIST: "/user/wishlist",
    ADD_CATEGORY: "/product/addCategory",
    GET_CATEGORY: "/product/categories",
    UPLOAD_IMAGE: "/product/image",
    ADD_PRODUCT: "/product/add",
    ADD_IMAGE: "/product/image",
    GET_PRODUCTS: "/product",
    CART: "/cart",
    ORDER: "/order",
    PLACE_ORDER: "/placeOrder",
    REVIEW: '/review',
    DASHBOARD_STATICS: "/dashboard/statics",
    OUT_OF_STOCK: "/dashboard/outOfStock",
    PRODUCT_WITH_MAX_ORDER: "/dashboard/maxorder",
    PENDING_ORDERS: "/dashboard/pendingOrders"
}
